
HashDict: HashDict.o main.o
	g++ HashDict.o main.o -o HashDict

HashDict.o: Node.h TimeInterval.h  HashDict.h HashDict.cpp
	g++ -c HashTable.cpp

main.o: main.cpp HashTable.h
	g++ -c main.cpp

clean:
	rm -f *.o
	rm HashTable
run: HashTable
	./HashTable
